services:
  - type: web
    name: wetalk-server
    env: docker
    region: singapore
    plan: free
    branch: v4.0-java
    dockerfilePath: ./Dockerfile
    healthCheckPath: /api/health
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: dev
      - key: JWT_SECRET
        generateValue: true
