// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: im.proto

package com.wetalk.im.codec;

public final class ImProtocol {
  private ImProtocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ImPacketOrBuilder extends
      // @@protoc_insertion_point(interface_extends:wetalk.im.ImPacket)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.wetalk.im.Header header = 1;</code>
     * @return Whether the header field is set.
     */
    boolean hasHeader();
    /**
     * <code>.wetalk.im.Header header = 1;</code>
     * @return The header.
     */
    com.wetalk.im.codec.ImProtocol.Header getHeader();
    /**
     * <code>.wetalk.im.Header header = 1;</code>
     */
    com.wetalk.im.codec.ImProtocol.HeaderOrBuilder getHeaderOrBuilder();

    /**
     * <code>bytes payload = 2;</code>
     * @return The payload.
     */
    com.google.protobuf.ByteString getPayload();
  }
  /**
   * Protobuf type {@code wetalk.im.ImPacket}
   */
  public  static final class ImPacket extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:wetalk.im.ImPacket)
      ImPacketOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ImPacket.newBuilder() to construct.
    private ImPacket(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ImPacket() {
      payload_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ImPacket();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ImPacket(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.wetalk.im.codec.ImProtocol.Header.Builder subBuilder = null;
              if (header_ != null) {
                subBuilder = header_.toBuilder();
              }
              header_ = input.readMessage(com.wetalk.im.codec.ImProtocol.Header.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(header_);
                header_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {

              payload_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wetalk.im.codec.ImProtocol.internal_static_wetalk_im_ImPacket_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wetalk.im.codec.ImProtocol.internal_static_wetalk_im_ImPacket_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.wetalk.im.codec.ImProtocol.ImPacket.class, com.wetalk.im.codec.ImProtocol.ImPacket.Builder.class);
    }

    public static final int HEADER_FIELD_NUMBER = 1;
    private com.wetalk.im.codec.ImProtocol.Header header_;
    /**
     * <code>.wetalk.im.Header header = 1;</code>
     * @return Whether the header field is set.
     */
    public boolean hasHeader() {
      return header_ != null;
    }
    /**
     * <code>.wetalk.im.Header header = 1;</code>
     * @return The header.
     */
    public com.wetalk.im.codec.ImProtocol.Header getHeader() {
      return header_ == null ? com.wetalk.im.codec.ImProtocol.Header.getDefaultInstance() : header_;
    }
    /**
     * <code>.wetalk.im.Header header = 1;</code>
     */
    public com.wetalk.im.codec.ImProtocol.HeaderOrBuilder getHeaderOrBuilder() {
      return getHeader();
    }

    public static final int PAYLOAD_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString payload_;
    /**
     * <code>bytes payload = 2;</code>
     * @return The payload.
     */
    public com.google.protobuf.ByteString getPayload() {
      return payload_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (header_ != null) {
        output.writeMessage(1, getHeader());
      }
      if (!payload_.isEmpty()) {
        output.writeBytes(2, payload_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (header_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getHeader());
      }
      if (!payload_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, payload_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.wetalk.im.codec.ImProtocol.ImPacket)) {
        return super.equals(obj);
      }
      com.wetalk.im.codec.ImProtocol.ImPacket other = (com.wetalk.im.codec.ImProtocol.ImPacket) obj;

      if (hasHeader() != other.hasHeader()) return false;
      if (hasHeader()) {
        if (!getHeader()
            .equals(other.getHeader())) return false;
      }
      if (!getPayload()
          .equals(other.getPayload())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasHeader()) {
        hash = (37 * hash) + HEADER_FIELD_NUMBER;
        hash = (53 * hash) + getHeader().hashCode();
      }
      hash = (37 * hash) + PAYLOAD_FIELD_NUMBER;
      hash = (53 * hash) + getPayload().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.wetalk.im.codec.ImProtocol.ImPacket parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wetalk.im.codec.ImProtocol.ImPacket parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wetalk.im.codec.ImProtocol.ImPacket parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wetalk.im.codec.ImProtocol.ImPacket parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wetalk.im.codec.ImProtocol.ImPacket parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wetalk.im.codec.ImProtocol.ImPacket parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wetalk.im.codec.ImProtocol.ImPacket parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.wetalk.im.codec.ImProtocol.ImPacket parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.wetalk.im.codec.ImProtocol.ImPacket parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.wetalk.im.codec.ImProtocol.ImPacket parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.wetalk.im.codec.ImProtocol.ImPacket parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.wetalk.im.codec.ImProtocol.ImPacket parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.wetalk.im.codec.ImProtocol.ImPacket prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code wetalk.im.ImPacket}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:wetalk.im.ImPacket)
        com.wetalk.im.codec.ImProtocol.ImPacketOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.wetalk.im.codec.ImProtocol.internal_static_wetalk_im_ImPacket_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.wetalk.im.codec.ImProtocol.internal_static_wetalk_im_ImPacket_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.wetalk.im.codec.ImProtocol.ImPacket.class, com.wetalk.im.codec.ImProtocol.ImPacket.Builder.class);
      }

      // Construct using com.wetalk.im.codec.ImProtocol.ImPacket.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (headerBuilder_ == null) {
          header_ = null;
        } else {
          header_ = null;
          headerBuilder_ = null;
        }
        payload_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.wetalk.im.codec.ImProtocol.internal_static_wetalk_im_ImPacket_descriptor;
      }

      @java.lang.Override
      public com.wetalk.im.codec.ImProtocol.ImPacket getDefaultInstanceForType() {
        return com.wetalk.im.codec.ImProtocol.ImPacket.getDefaultInstance();
      }

      @java.lang.Override
      public com.wetalk.im.codec.ImProtocol.ImPacket build() {
        com.wetalk.im.codec.ImProtocol.ImPacket result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.wetalk.im.codec.ImProtocol.ImPacket buildPartial() {
        com.wetalk.im.codec.ImProtocol.ImPacket result = new com.wetalk.im.codec.ImProtocol.ImPacket(this);
        if (headerBuilder_ == null) {
          result.header_ = header_;
        } else {
          result.header_ = headerBuilder_.build();
        }
        result.payload_ = payload_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.wetalk.im.codec.ImProtocol.ImPacket) {
          return mergeFrom((com.wetalk.im.codec.ImProtocol.ImPacket)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.wetalk.im.codec.ImProtocol.ImPacket other) {
        if (other == com.wetalk.im.codec.ImProtocol.ImPacket.getDefaultInstance()) return this;
        if (other.hasHeader()) {
          mergeHeader(other.getHeader());
        }
        if (other.getPayload() != com.google.protobuf.ByteString.EMPTY) {
          setPayload(other.getPayload());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.wetalk.im.codec.ImProtocol.ImPacket parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.wetalk.im.codec.ImProtocol.ImPacket) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.wetalk.im.codec.ImProtocol.Header header_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.wetalk.im.codec.ImProtocol.Header, com.wetalk.im.codec.ImProtocol.Header.Builder, com.wetalk.im.codec.ImProtocol.HeaderOrBuilder> headerBuilder_;
      /**
       * <code>.wetalk.im.Header header = 1;</code>
       * @return Whether the header field is set.
       */
      public boolean hasHeader() {
        return headerBuilder_ != null || header_ != null;
      }
      /**
       * <code>.wetalk.im.Header header = 1;</code>
       * @return The header.
       */
      public com.wetalk.im.codec.ImProtocol.Header getHeader() {
        if (headerBuilder_ == null) {
          return header_ == null ? com.wetalk.im.codec.ImProtocol.Header.getDefaultInstance() : header_;
        } else {
          return headerBuilder_.getMessage();
        }
      }
      /**
       * <code>.wetalk.im.Header header = 1;</code>
       */
      public Builder setHeader(com.wetalk.im.codec.ImProtocol.Header value) {
        if (headerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          header_ = value;
          onChanged();
        } else {
          headerBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.wetalk.im.Header header = 1;</code>
       */
      public Builder setHeader(
          com.wetalk.im.codec.ImProtocol.Header.Builder builderForValue) {
        if (headerBuilder_ == null) {
          header_ = builderForValue.build();
          onChanged();
        } else {
          headerBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.wetalk.im.Header header = 1;</code>
       */
      public Builder mergeHeader(com.wetalk.im.codec.ImProtocol.Header value) {
        if (headerBuilder_ == null) {
          if (header_ != null) {
            header_ =
              com.wetalk.im.codec.ImProtocol.Header.newBuilder(header_).mergeFrom(value).buildPartial();
          } else {
            header_ = value;
          }
          onChanged();
        } else {
          headerBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.wetalk.im.Header header = 1;</code>
       */
      public Builder clearHeader() {
        if (headerBuilder_ == null) {
          header_ = null;
          onChanged();
        } else {
          header_ = null;
          headerBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.wetalk.im.Header header = 1;</code>
       */
      public com.wetalk.im.codec.ImProtocol.Header.Builder getHeaderBuilder() {
        
        onChanged();
        return getHeaderFieldBuilder().getBuilder();
      }
      /**
       * <code>.wetalk.im.Header header = 1;</code>
       */
      public com.wetalk.im.codec.ImProtocol.HeaderOrBuilder getHeaderOrBuilder() {
        if (headerBuilder_ != null) {
          return headerBuilder_.getMessageOrBuilder();
        } else {
          return header_ == null ?
              com.wetalk.im.codec.ImProtocol.Header.getDefaultInstance() : header_;
        }
      }
      /**
       * <code>.wetalk.im.Header header = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.wetalk.im.codec.ImProtocol.Header, com.wetalk.im.codec.ImProtocol.Header.Builder, com.wetalk.im.codec.ImProtocol.HeaderOrBuilder> 
          getHeaderFieldBuilder() {
        if (headerBuilder_ == null) {
          headerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.wetalk.im.codec.ImProtocol.Header, com.wetalk.im.codec.ImProtocol.Header.Builder, com.wetalk.im.codec.ImProtocol.HeaderOrBuilder>(
                  getHeader(),
                  getParentForChildren(),
                  isClean());
          header_ = null;
        }
        return headerBuilder_;
      }

      private com.google.protobuf.ByteString payload_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes payload = 2;</code>
       * @return The payload.
       */
      public com.google.protobuf.ByteString getPayload() {
        return payload_;
      }
      /**
       * <code>bytes payload = 2;</code>
       * @param value The payload to set.
       * @return This builder for chaining.
       */
      public Builder setPayload(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        payload_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes payload = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearPayload() {
        
        payload_ = getDefaultInstance().getPayload();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:wetalk.im.ImPacket)
    }

    // @@protoc_insertion_point(class_scope:wetalk.im.ImPacket)
    private static final com.wetalk.im.codec.ImProtocol.ImPacket DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.wetalk.im.codec.ImProtocol.ImPacket();
    }

    public static com.wetalk.im.codec.ImProtocol.ImPacket getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ImPacket>
        PARSER = new com.google.protobuf.AbstractParser<ImPacket>() {
      @java.lang.Override
      public ImPacket parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ImPacket(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ImPacket> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ImPacket> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.wetalk.im.codec.ImProtocol.ImPacket getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface HeaderOrBuilder extends
      // @@protoc_insertion_point(interface_extends:wetalk.im.Header)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 cmd = 1;</code>
     * @return The cmd.
     */
    int getCmd();

    /**
     * <code>string msgId = 2;</code>
     * @return The msgId.
     */
    java.lang.String getMsgId();
    /**
     * <code>string msgId = 2;</code>
     * @return The bytes for msgId.
     */
    com.google.protobuf.ByteString
        getMsgIdBytes();

    /**
     * <code>string fromUid = 3;</code>
     * @return The fromUid.
     */
    java.lang.String getFromUid();
    /**
     * <code>string fromUid = 3;</code>
     * @return The bytes for fromUid.
     */
    com.google.protobuf.ByteString
        getFromUidBytes();

    /**
     * <code>string toUid = 4;</code>
     * @return The toUid.
     */
    java.lang.String getToUid();
    /**
     * <code>string toUid = 4;</code>
     * @return The bytes for toUid.
     */
    com.google.protobuf.ByteString
        getToUidBytes();

    /**
     * <code>int64 timestamp = 5;</code>
     * @return The timestamp.
     */
    long getTimestamp();

    /**
     * <code>int64 seqId = 6;</code>
     * @return The seqId.
     */
    long getSeqId();

    /**
     * <code>string devId = 7;</code>
     * @return The devId.
     */
    java.lang.String getDevId();
    /**
     * <code>string devId = 7;</code>
     * @return The bytes for devId.
     */
    com.google.protobuf.ByteString
        getDevIdBytes();
  }
  /**
   * Protobuf type {@code wetalk.im.Header}
   */
  public  static final class Header extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:wetalk.im.Header)
      HeaderOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Header.newBuilder() to construct.
    private Header(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Header() {
      msgId_ = "";
      fromUid_ = "";
      toUid_ = "";
      devId_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Header();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Header(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              cmd_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              msgId_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              fromUid_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              toUid_ = s;
              break;
            }
            case 40: {

              timestamp_ = input.readInt64();
              break;
            }
            case 48: {

              seqId_ = input.readInt64();
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              devId_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wetalk.im.codec.ImProtocol.internal_static_wetalk_im_Header_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wetalk.im.codec.ImProtocol.internal_static_wetalk_im_Header_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.wetalk.im.codec.ImProtocol.Header.class, com.wetalk.im.codec.ImProtocol.Header.Builder.class);
    }

    public static final int CMD_FIELD_NUMBER = 1;
    private int cmd_;
    /**
     * <code>int32 cmd = 1;</code>
     * @return The cmd.
     */
    public int getCmd() {
      return cmd_;
    }

    public static final int MSGID_FIELD_NUMBER = 2;
    private volatile java.lang.Object msgId_;
    /**
     * <code>string msgId = 2;</code>
     * @return The msgId.
     */
    public java.lang.String getMsgId() {
      java.lang.Object ref = msgId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        msgId_ = s;
        return s;
      }
    }
    /**
     * <code>string msgId = 2;</code>
     * @return The bytes for msgId.
     */
    public com.google.protobuf.ByteString
        getMsgIdBytes() {
      java.lang.Object ref = msgId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msgId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FROMUID_FIELD_NUMBER = 3;
    private volatile java.lang.Object fromUid_;
    /**
     * <code>string fromUid = 3;</code>
     * @return The fromUid.
     */
    public java.lang.String getFromUid() {
      java.lang.Object ref = fromUid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fromUid_ = s;
        return s;
      }
    }
    /**
     * <code>string fromUid = 3;</code>
     * @return The bytes for fromUid.
     */
    public com.google.protobuf.ByteString
        getFromUidBytes() {
      java.lang.Object ref = fromUid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fromUid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TOUID_FIELD_NUMBER = 4;
    private volatile java.lang.Object toUid_;
    /**
     * <code>string toUid = 4;</code>
     * @return The toUid.
     */
    public java.lang.String getToUid() {
      java.lang.Object ref = toUid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        toUid_ = s;
        return s;
      }
    }
    /**
     * <code>string toUid = 4;</code>
     * @return The bytes for toUid.
     */
    public com.google.protobuf.ByteString
        getToUidBytes() {
      java.lang.Object ref = toUid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        toUid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 5;
    private long timestamp_;
    /**
     * <code>int64 timestamp = 5;</code>
     * @return The timestamp.
     */
    public long getTimestamp() {
      return timestamp_;
    }

    public static final int SEQID_FIELD_NUMBER = 6;
    private long seqId_;
    /**
     * <code>int64 seqId = 6;</code>
     * @return The seqId.
     */
    public long getSeqId() {
      return seqId_;
    }

    public static final int DEVID_FIELD_NUMBER = 7;
    private volatile java.lang.Object devId_;
    /**
     * <code>string devId = 7;</code>
     * @return The devId.
     */
    public java.lang.String getDevId() {
      java.lang.Object ref = devId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        devId_ = s;
        return s;
      }
    }
    /**
     * <code>string devId = 7;</code>
     * @return The bytes for devId.
     */
    public com.google.protobuf.ByteString
        getDevIdBytes() {
      java.lang.Object ref = devId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        devId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (cmd_ != 0) {
        output.writeInt32(1, cmd_);
      }
      if (!getMsgIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, msgId_);
      }
      if (!getFromUidBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, fromUid_);
      }
      if (!getToUidBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, toUid_);
      }
      if (timestamp_ != 0L) {
        output.writeInt64(5, timestamp_);
      }
      if (seqId_ != 0L) {
        output.writeInt64(6, seqId_);
      }
      if (!getDevIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, devId_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (cmd_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, cmd_);
      }
      if (!getMsgIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, msgId_);
      }
      if (!getFromUidBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, fromUid_);
      }
      if (!getToUidBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, toUid_);
      }
      if (timestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, timestamp_);
      }
      if (seqId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, seqId_);
      }
      if (!getDevIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, devId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.wetalk.im.codec.ImProtocol.Header)) {
        return super.equals(obj);
      }
      com.wetalk.im.codec.ImProtocol.Header other = (com.wetalk.im.codec.ImProtocol.Header) obj;

      if (getCmd()
          != other.getCmd()) return false;
      if (!getMsgId()
          .equals(other.getMsgId())) return false;
      if (!getFromUid()
          .equals(other.getFromUid())) return false;
      if (!getToUid()
          .equals(other.getToUid())) return false;
      if (getTimestamp()
          != other.getTimestamp()) return false;
      if (getSeqId()
          != other.getSeqId()) return false;
      if (!getDevId()
          .equals(other.getDevId())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CMD_FIELD_NUMBER;
      hash = (53 * hash) + getCmd();
      hash = (37 * hash) + MSGID_FIELD_NUMBER;
      hash = (53 * hash) + getMsgId().hashCode();
      hash = (37 * hash) + FROMUID_FIELD_NUMBER;
      hash = (53 * hash) + getFromUid().hashCode();
      hash = (37 * hash) + TOUID_FIELD_NUMBER;
      hash = (53 * hash) + getToUid().hashCode();
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimestamp());
      hash = (37 * hash) + SEQID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSeqId());
      hash = (37 * hash) + DEVID_FIELD_NUMBER;
      hash = (53 * hash) + getDevId().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.wetalk.im.codec.ImProtocol.Header parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wetalk.im.codec.ImProtocol.Header parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wetalk.im.codec.ImProtocol.Header parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wetalk.im.codec.ImProtocol.Header parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wetalk.im.codec.ImProtocol.Header parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wetalk.im.codec.ImProtocol.Header parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wetalk.im.codec.ImProtocol.Header parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.wetalk.im.codec.ImProtocol.Header parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.wetalk.im.codec.ImProtocol.Header parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.wetalk.im.codec.ImProtocol.Header parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.wetalk.im.codec.ImProtocol.Header parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.wetalk.im.codec.ImProtocol.Header parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.wetalk.im.codec.ImProtocol.Header prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code wetalk.im.Header}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:wetalk.im.Header)
        com.wetalk.im.codec.ImProtocol.HeaderOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.wetalk.im.codec.ImProtocol.internal_static_wetalk_im_Header_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.wetalk.im.codec.ImProtocol.internal_static_wetalk_im_Header_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.wetalk.im.codec.ImProtocol.Header.class, com.wetalk.im.codec.ImProtocol.Header.Builder.class);
      }

      // Construct using com.wetalk.im.codec.ImProtocol.Header.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        cmd_ = 0;

        msgId_ = "";

        fromUid_ = "";

        toUid_ = "";

        timestamp_ = 0L;

        seqId_ = 0L;

        devId_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.wetalk.im.codec.ImProtocol.internal_static_wetalk_im_Header_descriptor;
      }

      @java.lang.Override
      public com.wetalk.im.codec.ImProtocol.Header getDefaultInstanceForType() {
        return com.wetalk.im.codec.ImProtocol.Header.getDefaultInstance();
      }

      @java.lang.Override
      public com.wetalk.im.codec.ImProtocol.Header build() {
        com.wetalk.im.codec.ImProtocol.Header result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.wetalk.im.codec.ImProtocol.Header buildPartial() {
        com.wetalk.im.codec.ImProtocol.Header result = new com.wetalk.im.codec.ImProtocol.Header(this);
        result.cmd_ = cmd_;
        result.msgId_ = msgId_;
        result.fromUid_ = fromUid_;
        result.toUid_ = toUid_;
        result.timestamp_ = timestamp_;
        result.seqId_ = seqId_;
        result.devId_ = devId_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.wetalk.im.codec.ImProtocol.Header) {
          return mergeFrom((com.wetalk.im.codec.ImProtocol.Header)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.wetalk.im.codec.ImProtocol.Header other) {
        if (other == com.wetalk.im.codec.ImProtocol.Header.getDefaultInstance()) return this;
        if (other.getCmd() != 0) {
          setCmd(other.getCmd());
        }
        if (!other.getMsgId().isEmpty()) {
          msgId_ = other.msgId_;
          onChanged();
        }
        if (!other.getFromUid().isEmpty()) {
          fromUid_ = other.fromUid_;
          onChanged();
        }
        if (!other.getToUid().isEmpty()) {
          toUid_ = other.toUid_;
          onChanged();
        }
        if (other.getTimestamp() != 0L) {
          setTimestamp(other.getTimestamp());
        }
        if (other.getSeqId() != 0L) {
          setSeqId(other.getSeqId());
        }
        if (!other.getDevId().isEmpty()) {
          devId_ = other.devId_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.wetalk.im.codec.ImProtocol.Header parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.wetalk.im.codec.ImProtocol.Header) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int cmd_ ;
      /**
       * <code>int32 cmd = 1;</code>
       * @return The cmd.
       */
      public int getCmd() {
        return cmd_;
      }
      /**
       * <code>int32 cmd = 1;</code>
       * @param value The cmd to set.
       * @return This builder for chaining.
       */
      public Builder setCmd(int value) {
        
        cmd_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 cmd = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearCmd() {
        
        cmd_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object msgId_ = "";
      /**
       * <code>string msgId = 2;</code>
       * @return The msgId.
       */
      public java.lang.String getMsgId() {
        java.lang.Object ref = msgId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          msgId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string msgId = 2;</code>
       * @return The bytes for msgId.
       */
      public com.google.protobuf.ByteString
          getMsgIdBytes() {
        java.lang.Object ref = msgId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msgId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string msgId = 2;</code>
       * @param value The msgId to set.
       * @return This builder for chaining.
       */
      public Builder setMsgId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        msgId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string msgId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMsgId() {
        
        msgId_ = getDefaultInstance().getMsgId();
        onChanged();
        return this;
      }
      /**
       * <code>string msgId = 2;</code>
       * @param value The bytes for msgId to set.
       * @return This builder for chaining.
       */
      public Builder setMsgIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        msgId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object fromUid_ = "";
      /**
       * <code>string fromUid = 3;</code>
       * @return The fromUid.
       */
      public java.lang.String getFromUid() {
        java.lang.Object ref = fromUid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          fromUid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string fromUid = 3;</code>
       * @return The bytes for fromUid.
       */
      public com.google.protobuf.ByteString
          getFromUidBytes() {
        java.lang.Object ref = fromUid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fromUid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string fromUid = 3;</code>
       * @param value The fromUid to set.
       * @return This builder for chaining.
       */
      public Builder setFromUid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        fromUid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string fromUid = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearFromUid() {
        
        fromUid_ = getDefaultInstance().getFromUid();
        onChanged();
        return this;
      }
      /**
       * <code>string fromUid = 3;</code>
       * @param value The bytes for fromUid to set.
       * @return This builder for chaining.
       */
      public Builder setFromUidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        fromUid_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object toUid_ = "";
      /**
       * <code>string toUid = 4;</code>
       * @return The toUid.
       */
      public java.lang.String getToUid() {
        java.lang.Object ref = toUid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          toUid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string toUid = 4;</code>
       * @return The bytes for toUid.
       */
      public com.google.protobuf.ByteString
          getToUidBytes() {
        java.lang.Object ref = toUid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          toUid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string toUid = 4;</code>
       * @param value The toUid to set.
       * @return This builder for chaining.
       */
      public Builder setToUid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        toUid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string toUid = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearToUid() {
        
        toUid_ = getDefaultInstance().getToUid();
        onChanged();
        return this;
      }
      /**
       * <code>string toUid = 4;</code>
       * @param value The bytes for toUid to set.
       * @return This builder for chaining.
       */
      public Builder setToUidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        toUid_ = value;
        onChanged();
        return this;
      }

      private long timestamp_ ;
      /**
       * <code>int64 timestamp = 5;</code>
       * @return The timestamp.
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>int64 timestamp = 5;</code>
       * @param value The timestamp to set.
       * @return This builder for chaining.
       */
      public Builder setTimestamp(long value) {
        
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 timestamp = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimestamp() {
        
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      private long seqId_ ;
      /**
       * <code>int64 seqId = 6;</code>
       * @return The seqId.
       */
      public long getSeqId() {
        return seqId_;
      }
      /**
       * <code>int64 seqId = 6;</code>
       * @param value The seqId to set.
       * @return This builder for chaining.
       */
      public Builder setSeqId(long value) {
        
        seqId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 seqId = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearSeqId() {
        
        seqId_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object devId_ = "";
      /**
       * <code>string devId = 7;</code>
       * @return The devId.
       */
      public java.lang.String getDevId() {
        java.lang.Object ref = devId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          devId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string devId = 7;</code>
       * @return The bytes for devId.
       */
      public com.google.protobuf.ByteString
          getDevIdBytes() {
        java.lang.Object ref = devId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          devId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string devId = 7;</code>
       * @param value The devId to set.
       * @return This builder for chaining.
       */
      public Builder setDevId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        devId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string devId = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearDevId() {
        
        devId_ = getDefaultInstance().getDevId();
        onChanged();
        return this;
      }
      /**
       * <code>string devId = 7;</code>
       * @param value The bytes for devId to set.
       * @return This builder for chaining.
       */
      public Builder setDevIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        devId_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:wetalk.im.Header)
    }

    // @@protoc_insertion_point(class_scope:wetalk.im.Header)
    private static final com.wetalk.im.codec.ImProtocol.Header DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.wetalk.im.codec.ImProtocol.Header();
    }

    public static com.wetalk.im.codec.ImProtocol.Header getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Header>
        PARSER = new com.google.protobuf.AbstractParser<Header>() {
      @java.lang.Override
      public Header parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Header(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Header> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Header> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.wetalk.im.codec.ImProtocol.Header getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_wetalk_im_ImPacket_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_wetalk_im_ImPacket_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_wetalk_im_Header_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_wetalk_im_Header_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\010im.proto\022\twetalk.im\">\n\010ImPacket\022!\n\006hea" +
      "der\030\001 \001(\0132\021.wetalk.im.Header\022\017\n\007payload\030" +
      "\002 \001(\014\"u\n\006Header\022\013\n\003cmd\030\001 \001(\005\022\r\n\005msgId\030\002 " +
      "\001(\t\022\017\n\007fromUid\030\003 \001(\t\022\r\n\005toUid\030\004 \001(\t\022\021\n\tt" +
      "imestamp\030\005 \001(\003\022\r\n\005seqId\030\006 \001(\003\022\r\n\005devId\030\007" +
      " \001(\tB!\n\023com.wetalk.im.codecB\nImProtocolb" +
      "\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_wetalk_im_ImPacket_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_wetalk_im_ImPacket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_wetalk_im_ImPacket_descriptor,
        new java.lang.String[] { "Header", "Payload", });
    internal_static_wetalk_im_Header_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_wetalk_im_Header_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_wetalk_im_Header_descriptor,
        new java.lang.String[] { "Cmd", "MsgId", "FromUid", "ToUid", "Timestamp", "SeqId", "DevId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
